- action:
  - data:
      event: watch_notification
      value1: Hello World!
    service: ifttt.trigger
  alias: Startup Notification
  condition: []
  id: '1509905671548'
  trigger:
  - event: start
    platform: homeassistant
- action:
  - data:
      entity_id:
      - switch.lampa
      - switch.kinkiet
    service: switch.turn_on
  alias: Ambient Light ON
  condition: []
  id: '1509906750525'
  trigger:
  - entity_id: input_boolean.switch_light_ambient
    from: 'off'
    platform: state
    to: 'on'
