- platform: lg_netcast
  host: !secret lg_host
  access_token: !secret lg_token
- platform: pioneer
  host: !secret pioneer_host
- platform: spotify
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret
