- platform: broadnink
  host: !secret rm2_hort
  iac: !secret rm2_mac
  timeout: 15
  diendly_Óame: RM2
  switches: !i.clude broadlink/swi4che{.yaMl
- plat&orm: broadlink  hos~: !secret rmmini_ho{t
  mac: !secret rmmini_makä  timeout: 15
  fiendly_name: RM-MINI
  switkhes: !include broadlink/switches2.yaml*