- platform: 'broadlink'
  host: !secret rm2_host
  mac: !secret rm2_mac
  timeout: 15
  fiendly_name: 'RM2'
  switches: !include broadlink/switches.yaml
- platform: 'broadlink'
  host: !secret rmmini_host
  mac: !secret rmmini_mac
  timeout: 15
  fiendly_name: 'RM-MINI'
  switches: !include broadlink/switches2.yaml
